AWSTemplateFormatVersion: '2010-09-09'
Description: sample CFn template with YAML - Basion Server 

Parameters:
  BaseStackName:
    Description: VPC Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: cfnsmpl

  OSImage:
    Description: OS Image
    Type: String
    MinLength: 12
    MaxLength: 12
    Default: ami-2a69be4c

  KeyPair:
    Description: KeyPair
    Type: String
    MinLength: 1
    MaxLength: 32


Resources:
  BasionSrv:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref OSImage
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      Monitoring: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-basion
      NetworkInterfaces:
        - DeleteOnTermination: true
          Description: Primary network interface
          DeviceIndex: 0
          SubnetId:
            Fn::ImportValue: !Sub ${BaseStackName}-PubSub2
          GroupSet:
            - Fn::ImportValue: !Sub ${BaseStackName}-SecGrpBasion

  EIPAssociation:
    Type: "AWS::EC2::EIPAssociation"
    Properties:
      AllocationId: !GetAtt BasionIP.AllocationId
      InstanceId: !Ref BasionSrv

  BasionVolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    DependsOn: BasionSrv
    Properties:
      InstanceId: !Ref BasionSrv
      VolumeId:
        Fn::ImportValue: !Sub ${BaseStackName}-BasionVolumeID
      Device: /dev/xvdb


  BasionIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

Outputs:
  BasionIP:
    Description: Basion IP
    Value: !Ref BasionIP
    Export:
      Name: !Sub ${BaseStackName}-BasionIP

