AWSTemplateFormatVersion: '2010-09-09'

Description: Sample CFn Template with YAML - Security

Parameters:
  BaseStackName:
    Description: VPC Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: cfnsmpl

Resources:
  SecGrpLB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecGrpLB
      GroupDescription: http access
      VpcId:
        Fn::ImportValue: !Sub ${BaseStackName}-VPCID

  SecGrpLBIn1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecGrpLB
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0


  SecGrpWeb:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecGrpWeb
      GroupDescription: vpc-ope ssh
      VpcId:
        Fn::ImportValue: !Sub ${BaseStackName}-VPCID

  SecGrpWebIn1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecGrpWeb
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !Ref SecGrpLB

  SecGrpWebIn2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecGrpWeb
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !Ref SecGrpBasion


  SecGrpDB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecGrpDB
      GroupDescription: MySQL
      VpcId:
        Fn::ImportValue: !Sub ${BaseStackName}-VPCID

  SecGrpDBIn1:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: SecGrpWeb
    Properties:
      GroupId: !Ref SecGrpDB
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId: !Ref SecGrpWeb


  SecGrpBasion:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecGrpBasion
      GroupDescription: SSH from restricted src
      VpcId:
        Fn::ImportValue: !Sub ${BaseStackName}-VPCID

  SecGrpBasionIn1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecGrpBasion
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0
      Description: Open to Global


Outputs:
  SecGrpWebID:
    Description: Security Group for Web
    Value: !Ref SecGrpWeb
    Export:
      Name: !Sub ${BaseStackName}-SecGrpWeb

  SecGrpLBID:
    Description: Security Group for LB
    Value: !Ref SecGrpLB
    Export:
      Name: !Sub ${BaseStackName}-SecGrpLB

  SecGrpDBID:
    Description: Security Group for DB
    Value: !Ref SecGrpDB
    Export:
      Name: !Sub ${BaseStackName}-SecGrpDB

  SecGrpBasionID:
    Description: Security Group for Basion
    Value: !Ref SecGrpBasion
    Export:
      Name: !Sub ${BaseStackName}-SecGrpBasion
