AWSTemplateFormatVersion: '2010-09-09'
Description: sample CFn template with YAML - AutoScale

Parameters:
  BaseStackName:
    Description: VPC Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: cfnsmpl

  OSImage:
    Description: Base AmazonLinux Image
    Type : AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  KeyPair:
    Description: KeyPair
    Type: String
    MinLength: 1
    MaxLength: 32

  DBUser:
    Description: Database Master User Name
    Type: String
    MinLength: 5
    MaxLength: 20

  DBPassword:
    Description: Database Master User Password
    Type: String
    MinLength: 5
    MaxLength: 20
    NoEcho: true

Resources:
  WpLC:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref OSImage
      SecurityGroups:
        - Fn::ImportValue: !Sub ${BaseStackName}-SecGrpWeb
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      AssociatePublicIpAddress: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum -y update
          sudo yum -y install httpd mysql php php-mysql php-mbstring
          sudo /sbin/chkconfig httpd on
          sudo /etc/init.d/httpd start
          wget http://ja.wordpress.org/latest-ja.tar.gz -O /tmp/latest-ja.tar.gz
          tar xvzf /tmp/latest-ja.tar.gz -C /var/www/html/ --strip-components 1
          sudo chown apache:apache -R /var/www/html

  WpASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub ${BaseStackName}-PubSub1
        - Fn::ImportValue: !Sub ${BaseStackName}-PubSub2
      LaunchConfigurationName:
        Ref: WpLC
      HealthCheckGracePeriod: 300
      MinSize: '1'
      MaxSize: '3'
      TargetGroupARNs:
        - Fn::ImportValue: !Sub ${BaseStackName}-WpTargetGroupARN
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 0
        MaxBatchSize: 1
        PauseTime: PT1M

