AWSTemplateFormatVersion: '2010-09-09'
Description: Sample CFn template with YAML - R53 Record - WP hostname

Parameters:
  R53StackName:
    Description: R53 Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: cfnsmpl-r53

  ALBStackName:
    Description: ALB Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: cfnsmpl-alb

Resources:
  RecMyDomainWp:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Fn::ImportValue: !Sub ${R53StackName}-MyDomainZoneId
      RecordSets:
        - Name: wp.yukitaka.org.
          Type: A
          AliasTarget:
            HostedZoneId: Z14GRHDCWA56QT
            DNSName:
              Fn::ImportValue: !Sub ${ALBStackName}-WpALBDNS

Outputs:
  WpDNS:
    Description: WP DNS Name
    Value: !Ref RecMyDomainWp
    Export:
      Name: !Sub ${AWS::StackName}-WpDNS
