AWSTemplateFormatVersion: '2010-09-09'
Description: sample CFn template with YAML - EC2

Parameters:
  BaseStackName:
    Description: VPC Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: cfnsmpl

  SecStackName:
    Description: Security Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: cfnsmpl-sec

  OSImage:
    Description: OS Image
    Type: String
    MinLength: 12
    MaxLength: 12
    Default: ami-2a69be4c


  BasionVolumeSnapshot:
    Description: Basion Volume Snapshot
    Type: String
    MinLength: 22
    MaxLength: 22

  KeyPair:
    Description: KeyPair
    Type: String
    MinLength: 1
    MaxLength: 32
    
  
Resources:
  BasionSrv:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref OSImage
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      Monitoring: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-basion
      NetworkInterfaces:
        - DeleteOnTermination: true
          Description: Primary network interface
          DeviceIndex: 0
          SubnetId:
            Fn::ImportValue: !Sub ${BaseStackName}-PubSub1
          GroupSet:
            - Fn::ImportValue: !Sub ${SecStackName}-SecGrpWeb

  EIPAssociation:
    Type: "AWS::EC2::EIPAssociation"
    Properties:
      AllocationId: !GetAtt BasionIP.AllocationId
      InstanceId: !Ref BasionSrv


  BasionVolume:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    DependsOn: BasionSrv
    Properties:
      Size: 10
      VolumeType: gp2
      AvailabilityZone: !GetAtt BasionSrv.AvailabilityZone
      SnapshotId: !Ref BasionVolumeSnapshot
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-BasionVolume

  BasionVolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    DependsOn:
      - BasionVolume
      - BasionSrv
    Properties:
      InstanceId: !Ref BasionSrv
      VolumeId: !Ref BasionVolume
      Device: /dev/xvdb


  BasionIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

Outputs:
  BasionIP:
    Description: Basion IP
    Value: !Ref BasionIP
    Export:
      Name: !Sub ${AWS::StackName}-BasionIP

